export const OPEN_BROWSER = "OPEN_BROWSER";
export const GET_VALUE_GLOBAL_STORAGE = "GET_VALUE_GLOBAL_STORAGE";
export const SET_VALUE_GLOBAL_STORAGE = "SET_VALUE_GLOBAL_STORAGE";

// receiving message
export const RECEIVE_VALUE_GLOBAL_STORAGE = "RECEIVE_VALUE_GLOBAL_STORAGE";
