export const OPEN_BROWSER = "OPEN_BROWSER";
export const CHANGE_THEME = "CHANGE_THEME";
export const SET_GIT_INFO = "SET_GIT_INFO";
export const GET_VALUE_GLOBAL_STORAGE = "GET_VALUE_GLOBAL_STORAGE";
export const SET_VALUE_GLOBAL_STORAGE = "SET_VALUE_GLOBAL_STORAGE";
export const SEND_VALUE_GLOBAL_STORAGE = "SEND_VALUE_GLOBAL_STORAGE";
