export const CHECK_GITHUB_INSTALLATIONS = "CHECK_GITHUB_INSTALLATIONS";
export const RETRIEVE_GITHUB_REPOSITORIES = "RETRIEVE_GITHUB_REPOSITORIES";
export const POPULATE_GITHUB_CONTEXT = "POPULATE_GITHUB_CONTEXT";
