export const CHECK_GITHUB_INSTALLATIONS = "CHECK_GITHUB_INSTALLATIONS";
export const RETRIEVE_GITHUB_REPOSITORIES = "RETRIEVE_GITHUB_REPOSITORIES";
export const UPDATE_GITHUB_FILE_CONTEXT = "UPDATE_GITHUB_FILE_CONTEXT";
