export const GET_USER = "GET_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const USER_ATTACH_WORKSPACE = "USER_ATTACH_WORKSPACE";
export const USER_REMOVE_WORKSPACE = "USER_REMOVE_WORKSPACE";
