export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const GET_WORKSPACE = "GET_WORKSPACE";
export const RETRIEVE_WORKSPACES = "RETRIEVE_WORKSPACES";
export const EDIT_WORKSPACE = "EDIT_WORKSPACE";
export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
